### ISSUE TITLE
Error al ejecutar sentencias CALL 

### ISSUE THREAD

**Issue by Santyagomc** [Cesar-1e/SwiftFusePHP#1]
Al momento de trabajar con procedimientos utilizando las sentencias **CALL de MySQL** en las consultas, me di cuenta de que validando la existencia de los datos retorna el siguiente error en la conexión: 

`SQLSTATE[HY000]: General error: 2014 Cannot execute queries while there are pending result sets. Consider unsetting the previous PDOStatement or calling PDOStatement::closeCursor()`

Analizando, me percato de que todo se ejecuta de manera correcta siempre y cuando se ejecute por primera vez. Utilizando la herramienta de **Xdebug**, se puede ver como al momento de ejecutar y frenar el código, todo funciona de forma correcta, pero al continuar con la ejecución los datos que llegan desde la consulta ya no tienen existencia, por lo que se pierden y el proceso no da ninguna respuesta frente a los datos consultados.

**Comment by Cesar-1e** [comment]
Gracias por reportar el error.
Al revisar detalladamente se confirma que se genera un error al ejecutar por segunda vez, con sentencias **CALL**

**Comment by Cesar-1e** [comment]
Hola @Santyagomc te informamos que ha sido solucionado 💯 

Te adjunto el link: https://github.com/Cesar-1e/Framework_PHP/tree/b4129eb510a4aabe4f6aa355ffa48a50ee9963f6
