### ISSUE TITLE
Inconsistencia al momento de guardar archivos con la funcion saveFile

### ISSUE THREAD

**Issue by Santyagomc** [Cesar-1e/SwiftFusePHP#2]
Al momento de utilizar la función `saveFile()` en el archivo `configurar.php ` no esta retornando los nombres de los archivos que almacena.
Analizando la trayectoria de los commits, noto que en la misma función no se encuentra el `return $nombreArchivos ` al finalizarla. 

Esto pasa desde que se aplico el commit 9bb1144 en el cual se elimino esta sentencia.

**Comment by Cesar-1e** [comment]
Gracias por reportar la falla. Ya se encuentra solucionado en el siguiente commit https://github.com/Cesar-1e/SwiftFusePHP/commit/3e09b63cc9701034fac9a7d209ba1cfcfc02ee63#diff-44abfb65ee5dd2f66268ee0923708eda015dd201352210f4c047921521827a86
